FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY server/package.json server/package-lock.json ./server/
RUN npm ci --prefix server

COPY . .

ARG VITE_SUPABASE_PROJECT_ID=""
ARG VITE_SUPABASE_URL=""
ARG VITE_SUPABASE_ANON_KEY=""
ARG VITE_OPENROUTER_API_KEY=""
ARG VITE_OPENROUTER_MODEL=""
ARG VITE_OPENROUTER_FALLBACK_MODELS=""
ARG VITE_OPENROUTER_SITE_URL=""
ARG VITE_OPENROUTER_SITE_TITLE=""
ARG VITE_OPENROUTER_REQUEST_TIMEOUT_MS=""
ARG VITE_GOOGLE_MAPS_API_KEY=""
ARG VITE_LOCATIONIQ_API_KEY=""
ARG VITE_API_BASE_URL=""
ARG VITE_SERVER_URL=""

ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_OPENROUTER_API_KEY=$VITE_OPENROUTER_API_KEY
ENV VITE_OPENROUTER_MODEL=$VITE_OPENROUTER_MODEL
ENV VITE_OPENROUTER_FALLBACK_MODELS=$VITE_OPENROUTER_FALLBACK_MODELS
ENV VITE_OPENROUTER_SITE_URL=$VITE_OPENROUTER_SITE_URL
ENV VITE_OPENROUTER_SITE_TITLE=$VITE_OPENROUTER_SITE_TITLE
ENV VITE_OPENROUTER_REQUEST_TIMEOUT_MS=$VITE_OPENROUTER_REQUEST_TIMEOUT_MS
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_LOCATIONIQ_API_KEY=$VITE_LOCATIONIQ_API_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_SERVER_URL=$VITE_SERVER_URL

RUN npm run build

FROM node:20-bookworm-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY server/package.json server/package-lock.json ./server/
RUN npm ci --omit=dev --prefix server

COPY --from=build /app/server/index.js ./server/index.js
COPY --from=build /app/server/lib ./server/lib
COPY --from=build /app/server/middleware ./server/middleware
COPY --from=build /app/server/routes ./server/routes
COPY --from=build /app/dist ./dist

EXPOSE 8080

CMD ["node", "server/index.js"]
